version: "3.8"

networks:
  projectmicro_default:
    name: projectmicro_default

services:
  configserver:
    build:
      context: ./configserver
    ports:
      - "8888:8888"
    networks:
      - projectmicro_default

  discovery:
    build:
      context: ./commande-livreur-app/discovery
    ports:
      - "8761:8761"
    networks:
      - projectmicro_default

  gateway_api:
    build:
      context: ./commande-livreur-app/gateway_api
    ports:
      - "8088:8088"
    depends_on:
      - configserver
    networks:
      - projectmicro_default
