version: "3.8"

networks:
  projectmicro_default:
    name: projectmicro_default

services:
  configserver:
    build:
      context: ./configserver
    ports:
      - "8888:8888"
    networks:
      - projectmicro_default

  discovery:
    build:
      context: ./commande-livreur-app/discovery
    ports:
      - "8761:8761"
    networks:
      - projectmicro_default

  gateway_api:
    build:
      context: ./commande-livreur-app/gateway_api
    ports:
      - "8088:8088"
    depends_on:
      - configserver
      - discovery
    networks:
      - projectmicro_default

  mysql-commande:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commande_db
    ports:
      - "3306:3306"
    networks:
      - projectmicro_default

  mongo-livreur:
    image: mongo:5
    container_name: mongo-livreur
    ports:
      - "27017:27017"
    networks:
      - projectmicro_default

  service-commande:
    build:
      context: ./commande-livreur-app/ServiceCommande
    ports:
      - "9090:9090"
    depends_on:
      - mysql-commande
      - configserver
      - discovery
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - projectmicro_default

  service-livreur:
    build:
      context: ./commande-livreur-app/serviceLivreur
    ports:
      - "9091:9091"
    depends_on:
      - mongo-livreur
      - configserver
      - discovery
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - projectmicro_default
